version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hello_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: sam3ctc/hello-world
    container_name: flask_app
    ports:
      - "8080:8080"
    environment:
      MYSQL_SERVER: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: hello_db
    depends_on:
      - mysql

volumes:
  mysql_data:
