namespace: hello-world

replicaCount: 2

image:
  repository: your-dockerhub-username/hello-world-app
  tag: latest
  pullPolicy: IfNotPresent

mysql:
  image: mysql:8.0
  database: hello_db
  username: root
  password: root1
  storageSize: 10Gi
  storageClass: azure-disk

ingress:
  enabled: true
  host: ""

