namespace: hello-world

replicaCount: 1

image:
  repository: sam3ct/hello-world
  tag: latest
  pullPolicy: IfNotPresent

mysql:
  image: mysql:8.0
  database: hello_db
  username: root
  password: root
  storageSize: 10Gi

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: ""

