apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hello-world
  type: ClusterIP
